### ISSUE TITLE
Add links to two other github projects

### ISSUE THREAD

**Issue by kennetn** [tmrobert8/openhab2-addons#1]
In the README-SCALAR.md page under GITHUB Information there is a reference to two other github projects called sonydevices/openHAB and sonydevices/dev. I suggest that you change the text to an actual clickable link to "https://github.com/sonydevices/openHAB/issues" and "https://github.com/sonydevices/dev/issues" so that it is easy for no github experienced users to find that actual data created when they use the binding.

**Comment by tmrobert8** [comment]
Just added - thanks for the feedback
