### ISSUE TITLE
Minor corrections for README.md

### ISSUE THREAD

**Issue by kennetn** [tmrobert8/openhab2-addons#2]
1) In the section Simple IP
is says "For specifics on Scalar -"
I suggest "For specifics "

2) In the section IRCC
Says: "over the the Scalar API "
I suggest "over to the Scalar API"

3) In the section IRCC
is says "For specifics on Scalar -"
I suggest "For specifics "

4) In the section DAIL
is says "For specifics on Scalar -"
I suggest "For specifics "

**Comment by tmrobert8** [comment]
Thanks for the help - these have been corrected
