### ISSUE TITLE
Missing Thing in the full example

### ISSUE THREAD

**Issue by kennetn** [tmrobert8/openhab2-addons#3]
In the full examples of what to write in the thing file do you not need to write Thing in front of the sony. Maybe there is some way it will work but I think the examples are more self contained if you add Thing.
Currently is says:
sony:scalar:home [ deviceAddress="http://192.168.1.123:52323/dmr.xml", deviceMacAddress="aa:bb:cc:dd:ee:ff", refresh=-1 ]

I think is needs to be:
Thing sony:scalar:home [ deviceAddress="http://192.168.1.123:52323/dmr.xml", deviceMacAddress="aa:bb:cc:dd:ee:ff", refresh=-1 ]

**Comment by tmrobert8** [comment]
Not needed but it's more clear this way - I'll add it.  Thanks!
