### ISSUE TITLE
Configure preshared keys

### ISSUE THREAD

**Issue by kennetn** [tmrobert8/openhab2-addons#4]
Is there a way to configure a preshared key for the SCALAR interface in the Things file ?

**Comment by andiwirs** [comment]
Yes just fill in the preshared key (configured on the TV) as "accessCode" in the Scalar Thing definition.
Please refer to section [Thing Configuration](https://github.com/tmrobert8/openhab-addons/blob/1234-Sony/bundles/org.openhab.binding.sony/README-SCALAR.md#thing-configuration) in the README-SCALAR.md

**Comment by tmrobert8** [comment]
As @Andirs55 said!
