### ISSUE TITLE
Empty reponse (or unsupported command): '*SEPIPI################'

### ISSUE THREAD

**Issue by kduytsch** [tmrobert8/openhab2-addons#6]
I was looking in the code to understand how the refresh is working (because the power ON/OFF state doesn't work) and I noticed that there are a bunch of request sent for refresh on periodic interval. Based on that I noticed :

1) SEPIPI isn't a supported command (not in https://pro-bravia.sony.net/develop/integrate/ssip/command-definitions/index.html)
2) refreshState() isn't refreshing the POWR (probably because there is a refreshPower() )
refreshState() {
        refreshVolume();
        refreshChannel();
        refreshTripletChannel();
        refreshInputSource();
        refreshPictureInPicture();
    }
3) refreshPower() isn't called (except if there is a IRCC command sent ?)

## Expected Behavior
1) Remove SEPIPI (except if actually implemented in some other systems, but at least not part of doc)
2) Allow a POWR refresh periodicaly (either via the refreshState() which runs every 30s or so)

## Your Environment
Working with latest available jar file on OH 2.5 (latest)

**Comment by tmrobert8** [comment]
Thanks for the comments:
1. PIPI (picture in picture) is definitely a command for some bravias - just not your's I bet.  There are quite a few commands that aren't documented
2. Interesting - don't know why power wasn't being refreshed.  Latest version will correct that
